; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-s3-devkitc-1-psram]
board_build.arduino.memory_type = qio_opi  ; NEEDED FOR 8MB PSRAM (N16R8)
extends                 = env:esp32-s3-devkitc-1


[env:esp32-s3-devkitc-1]
board = ESP-General
board_build.partitions = custom_8Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/ESP-General>
build_flags =
    ${env.build_flags}
    -Iboards/ESP-General
    -DUSB_as_HID=1

    ; grove pins
    -DGROVE_SDA=8
    -DGROVE_SCL=9

    ; ir led pin
    -DIR_TX_PINS='{{"M5 IR Mod", GROVE_SDA}}'
    -DIR_RX_PINS='{{"M5 IR Mod", GROVE_SCL}}'
    -DTXLED=40
    -DLED_ON=HIGH
    -DLED_OFF=LOW

    ; sd card pins
    -DSDCARD_CS=13
    -DSDCARD_SCK=SPI_SCK_PIN
    -DSDCARD_MISO=SPI_MISO_PIN
    -DSDCARD_MOSI=SPI_MOSI_PIN

    ; tft vars
    -DROTATION=1
    -DBACKLIGHT=21
    -DMINBRIGHT=160
    -DSMOOTH_FONT=1
    -DTFT_DISPON=0x29
    -DTFT_DISPOFF=0x28
    -DTFT_CS=5
    -DTFT_DC=4
    -DTFT_RST=2
    -DTOUCH_CS=-1
    -DTFT_MOSI=SPI_MOSI_PIN
    -DTFT_SCLK=SPI_SCK_PIN
    -DTFT_BL=21
    -DTFT_MISO=SPI_MISO_PIN
    ; text sizes
    -DFP=1
    -DFM=2
    -DFG=3
    ; ui control buttons
    -DBTN_PREV=34
    -DBTN_NEXT=35
    -DBTN_SEL=36
    -DBTN_ESC=37
    -DBTN_ALIAS='"OK"'

    ;CC1101 SPI connection pins
    -DUSE_CC1101_VIA_SPI
    -DCC1101_GDO0_PIN=9
    -DCC1101_SS_PIN=SPI_SS_PIN
    -DCC1101_MOSI_PIN=SPI_MOSI_PIN
    -DCC1101_SCK_PIN=SPI_SCK_PIN
    -DCC1101_MISO_PIN=SPI_MISO_PIN

    ; nRF24
    -DUSE_NRF24_VIA_SPI
    -DNRF24_CE_PIN=6
    -DNRF24_SS_PIN=7
    -DNRF24_MOSI_PIN=SPI_MOSI_PIN
    -DNRF24_SCK_PIN=SPI_SCK_PIN
    -DNRF24_MISO_PIN=SPI_MISO_PIN

    ; SPI bus alias
    -DSPI_SCK_PIN=12
    -DSPI_MOSI_PIN=11
    -DSPI_MISO_PIN=13
    -DSPI_SS_PIN=10

    ; Device name
    -DDEVICE_NAME='"ESP32-S3 DevkitC"'

lib_deps =
    ${env.lib_deps}
    TFT_eSPI
